config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home'

  get 'pages/contacts', to: 'pages#contacts'
  get 'pages/about', to: 'pages#about'
  get 'pages/terms_and_conditions', to: 'pages#terms_and_conditions'

  devise_for :users
  resources :users, only: [:show] do

  	member do
  		get 'edit_profile'
  		patch 'update_profile'
  		get 'edit_avatar'
  		patch 'update_avatar'
  	end
    
  end

  resources :apartments do
    resources :photos, only: [:destroy]
    resources :bookings, only: [:new] #add bookings new under apartments

    collection do
      get 'district/:district', to: 'apartments#index_district'
    end

    member do
      get 'sold', to: 'apartments#sold'
    end
  end

  resources :bookings, except: [:new] do #remove new from bookings
    resources :payments, only: [:new, :create]
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :apartment

  monetize :price_cents
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_apartment, only: [:new]

  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def show
    authorize @booking
  end

  def new
    @booking = Booking.new
    @booking.apartment = @apartment
    authorize @booking
  end

  def edit
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.state = "pending"
    @booking.user = current_user
    @booking.price = 100

    authorize @booking

    if @booking.save
      redirect_to new_booking_payment_path(@booking), notice: 'Redirecting to payment processing.'
    else
      render :new, alert: 'Error on creating booking.'
    end
    
  end

  def update
    authorize @booking
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
      # send email if booking is updated
      send_amendment_email(@booking)
    else
      render :edit, alert: 'Error on updating booking.'
    end
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'

    #TODO: send an email upon booking cancel
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def set_apartment
      @apartment = Apartment.find(params[:apartment_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:book_date, :state, :book_time, :content, :location, :user_id, :apartment_id)
    end

    # Group email groups into meaningful actions
    def send_amendment_email(booking)
      BookingMailer.with(booking_id: booking.id).amendment_host.deliver_later
      BookingMailer.with(booking_id: booking.id).amendment_user.deliver_later
    end
end

app/views/bookings/_form.html.erb
<!-- TO ADJUST TO BOOKING FORM -->

<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :book_date %>
    <%= f.input :book_time %>
    <%= f.input :location, label: "Meet up location" %>
    <%= f.input :content, label: "Leave a message to owner" %>
    <%= f.input :apartment_id, as: :hidden %> <!-- hide the selected apartment -->
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<div class="container my-4">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>Editing Booking</h1>

      <%= render 'form', booking: @booking %>

      <%= link_to 'Show', @booking, :class => 'btn btn-primary'  %>
      <%= link_to 'Back', bookings_path, :class => 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<!-- ADJUST TO BOOKING INDEX, USE APARTMENT #INDEX AS BASE -->
<div class="container my-4">
    <h1>My Bookings</h1>
    <% @bookings.each do |booking| %>
    <div class="card rounded-lg w-100 my-3">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <h4 class="my-3">
                        <%= booking.apartment.description? ? booking.apartment.description : booking.apartment.address  %>
                    </h4>
                </div>
                <div class="col-6 col-md-3">
                    <div>
                        <small>User:</small><br>
                        <%= booking.user.full_name %>
                    </div>
                </div>
                <div class="col-6 col-md-3">
                    <div>
                        <small>Host:</small><br>
                        <%= booking.apartment.user.full_name %>
                    </div>
                </div>
                <div class="col-6 col-md-3">
                    <small>Meetup time</small><br>
                    <%= booking.book_date %><br>
                    <%= booking.book_time.strftime("%H:%M") %>
                </div>
                <div class="col-6 col-md-3">
                    <small>Meetup location</small><br>
                    <%= booking.location %>
                </div>
                <div class="col-6 col-md-3">
                    <small>Message</small><br>
                    <%= simple_format(booking.content) %>
                </div>
                <div class="col-6 col-md-3 py-2">
                    <% if policy(booking).show? %>
                    <%= link_to 'Details', booking_path(booking), class: "btn btn-primary btn-sm my-1" %>
                    <% end %>
                    <% if policy(booking).edit? %>
                    <%= link_to 'Edit', edit_booking_path(booking), class: "btn btn-primary btn-sm my-1" %>
                    <% end %>
                    <% if policy(booking).destroy? %>
                    <%= link_to 'Destroy', booking_path(booking), class: "btn btn-danger btn-sm my-1", method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <% end %>
    <br>
    <% if policy(Booking).create? %>
    <%#= link_to 'New Booking', new_booking_path, :class => 'btn btn-primary' %>
    <!-- this requires another form to select apartment (admin use?) -->
    <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container my-4">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h1>New Booking</h1>

            <h2>We charge HK$100 for each viewing appointment</h2>

            <%= render 'form', booking: @booking %>
            <!-- <p> Your booking is successfully processed!</p> --> <!-- It's not processed yet! The process take place at create action -->
            <%= link_to 'Back', bookings_path, class: "btn btn-primary my-4" %>
            <%#= link_to 'Edit', edit_booking_path %> <!-- We cannot edit the booking before it is created! -->
        </div>
    </div>
</div>

app/views/bookings/show.html.erb
<div class="container my-4">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <div class="card rounded-lg w-100 my-5">
                <div class="card-body">
                    <h2 class="my-4">Booking has been confirmed!</h2>
                    <p>
                        <small>Apartment</small><br>
                        <%= @booking.apartment.description? ? @booking.apartment.description : @booking.apartment.address  %>
                    </p>
                    <p>
                        <small>User:</small><br>
                        <%= @booking.user.full_name %>
                    </p>
                    <p>
                        <small>Host:</small><br>
                        <%= @booking.apartment.user.full_name %>
                    </p>
                    <p>
                        <small>Date of Booking</small><br>
                        <%= @booking.book_date %>
                    </p>
                    <p>
                        <small>Time of Booking</small><br>
                        <%= @booking.book_time.strftime("%H:%M") %>
                    </p>
                    <p>
                        <small>Meeting Location</small><br>
                        <%= @booking.location %>
                    </p>
                    <p>
                        <small>Message</small><br>
                        <%= @booking.content %>
                    </p>
                </div>
            </div>
            <%= link_to 'Edit', edit_booking_path(@booking), :class => 'btn btn-primary my-2' %><br>
            <%= link_to 'View my bookings', bookings_path, :class => 'btn btn-secondary my-2' %>
        </div>
    </div>
</div>