config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home'

  get 'pages/contacts', to: 'pages#contacts'
  get 'pages/about', to: 'pages#about'
  get 'pages/terms_and_conditions', to: 'pages#terms_and_conditions'

  devise_for :users
  resources :users, only: [:show] do

  	member do
  		get 'edit_profile'
  		patch 'update_profile'
  		get 'edit_avatar'
  		patch 'update_avatar'
  	end
    
  end

  resources :apartments do
    resources :photos, only: [:destroy]
    resources :bookings, only: [:new] #add bookings new under apartments

    collection do
      get 'district/:district', to: 'apartments#index_district'
    end

    member do
      get 'sold', to: 'apartments#sold'
    end
  end

  resources :bookings, except: [:new] do #remove new from bookings
    resources :payments, only: [:new, :create]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :booking
  has_many :apartment

  mount_uploader :avatar, AvatarUploader

  #combine and capitalize first_name + last_name, to full_name
  def full_name
    if first_name? && last_name?
      name_words = first_name.split(" ") + last_name.split(" ")
      return name_words.map{ |w| w.capitalize }.join(" ")
    else
      return email
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:show, :edit_profile, :update_profile, :edit_avatar, :update_avatar]

	def show
	end

	def edit_profile
	end

	def update_profile
		if @user.update(profile_params)
		  redirect_to user_path(@user), notice: 'Profile updated.'
		else
		  render :edit_profile, alert: 'Error updating profile.'
		end
	end

	def edit_avatar
	end

	def update_avatar
		if @user.update(avatar_params)
		  redirect_to user_path(@user), notice: 'Avatar uploaded.' #user/show page
		else
		  render :edit_avatar, alert: 'Error uploading avatar.'
		end
	end

	private

	def set_user
    	@user = User.find(params[:id])
    	authorize @user # jason has put authorize in here since it is repeated in all user actions
	end

	def profile_params
		params.require(:user).permit(:phone, :first_name, :last_name, :date_of_birth, :gender)
	end

	def avatar_params
		params.require(:user).permit(:avatar)
	end
end

app/views/users/edit_avatar.html.erb
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h1 class="my-4">Edit Avatar</h1>

        <%= simple_form_for(@user, url: update_avatar_user_path) do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
                <%= f.input :avatar,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "Please upload your profile picture" }%>
                <%= f.input :avatar_cache, as: :hidden %>
            </div>
            <div class="form-actions">
                <%= f.button :submit, 'Save Changes', :class=>"btn btn-primary w-100" %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/edit_profile.html.erb
<div class="row">
    <div class="col-md-6 offset-md-3">
    	<h1 class="my-4">Edit Profile</h1>
        <%= simple_form_for(@user, :url => update_profile_user_path, html: { class: 'form' }) do |f| %>
	        <%= f.input :first_name, required: true %>
	        <%= f.input :last_name, required: true %>
	        <%= f.input :date_of_birth, as: :date, start_year: Date.today.year - 50, end_year: Date.today.year, required: true, label:"Date of Birth" %>
	        <%= f.input :gender, required: true, collection:["Male", "Female"] %>
	        <%= f.input :phone, required: true, label:"Contact Number" %>
	        <div class="my-4"></div>
	        <%= f.button :submit, 'Save Changes', :class=>"btn btn-primary w-100" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<h1>users#show</h1>

<h2>User : <%= @user.first_name %> <%=@user.last_name %></h2>
<h2>Date of Birth: <%=@user.date_of_birth %></h2>
<h2>Email : <%=@user.email %></h2>
<h2>Gender : <%=@user.gender %></h2>

<h2><% if @user.avatar.present? %>
    <%= cl_image_tag @user.avatar, :cloud_name => "preface", :transformation => { :width => 100, :crop => "pad" }, :class=>"avatar-original"%>
<% else %>
    <%= image_tag "shared/avatar.png", :class=>"avatar-original"%>
<% end %></h2>

<%= link_to 'Edit Profile', edit_profile_user_path(@user), class: "btn btn-primary " %>
<%= link_to 'Edit Avatar', edit_avatar_user_path(@user), class: "btn btn-primary " %>