config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home'

  get 'pages/contacts', to: 'pages#contacts'
  get 'pages/about', to: 'pages#about'
  get 'pages/terms_and_conditions', to: 'pages#terms_and_conditions'

  devise_for :users
  resources :users, only: [:show] do

  	member do
  		get 'edit_profile'
  		patch 'update_profile'
  		get 'edit_avatar'
  		patch 'update_avatar'
  	end
    
  end

  resources :apartments do
    resources :photos, only: [:destroy]
    resources :bookings, only: [:new] #add bookings new under apartments

    collection do
      get 'district/:district', to: 'apartments#index_district'
    end

    member do
      get 'sold', to: 'apartments#sold'
    end
  end

  resources :bookings, except: [:new] do #remove new from bookings
    resources :payments, only: [:new, :create]
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-house-finder">

  <!-- top left link with logo -->
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    House Finder
  <% end %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">

  <div class="flex-grow-1 d-flex">
    
    <!-- search form with styles -->
    <%= form_tag apartments_path, :method => :get, :class => 'form-inline flex-nowrap bg-light mx-0 mx-lg-auto rounded p-1' do %>​
      <%= text_field_tag :query, params[:query], class: "form-control mr-sm-2", placeholder: "Find an apartment" %>
      <button class="btn btn-primary" type="submit">Search</button>
    <% end %>
  
</div>
  <!-- TODO : SEARCH BAR -->

      <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

         <li class="dropdown nav-link">
          <a id="navbar_apartment_dropdown" class="dropdown nav-item" style="cursor: pointer;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            APARTMENTS
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbar_apartment_dropdown ">
            <li>
              <%= link_to "View Apartments", apartments_path, class: "nav-link" %>
            </li>
            <% if policy(Apartment).create? %>
              <li>
                <%= link_to "New Apartment", new_apartment_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </li>


        <li class="dropdown nav-link">
          <a id="navbar_booking_dropdown" class="dropdown nav-item" style="cursor: pointer;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            BOOKINGS
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbar_booking_dropdown ">
            <li>
              <%= link_to 'My Bookings', bookings_path, class: "nav-link" %>
            </li>
          </ul>
        </li>
      <% end %>


      <li class="dropdown nav-link">
        <a id="navbar_static_dropdown" class="dropdown nav-item" style="cursor: pointer;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ABOUT
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbar_static_dropdown ">
          <li>
            <%= link_to "About Us", pages_about_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Contacts", pages_contacts_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Terms", pages_terms_and_conditions_path, class: "nav-link" %>
          </li>
        </ul>
      </li>

      <% if user_signed_in? %>

        <li class="dropdown">
          <a id="navbar_static_dropdown" class="dropdown nav-item ml-2" style="cursor: pointer;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="navbar-text nav-item active mr-2"><%= current_user.full_name %></span>
            <% if current_user.avatar.present? %>
                <%= cl_image_tag current_user.avatar, :cloud_name => "preface", :transformation => { :width => 100, :height=> 100, :crop => "fill" }, :class=>"avatar-bordered", 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
                <%= image_tag "shared/avatar.png", :class=>"avatar-bordered", 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbar_static_dropdown ">
            <li><%= link_to "Edit Profile", edit_profile_user_path(current_user), class: "nav-link" %></li>
            <li><%= link_to "Edit Avatar", edit_avatar_user_path(current_user), class: "nav-link" %></li>
            <li><%= link_to "Change Password", edit_user_registration_path, class: "nav-link" %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
          </ul>
        </li>


      <% else %>

        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>