config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home'

  get 'pages/contacts', to: 'pages#contacts'
  get 'pages/about', to: 'pages#about'
  get 'pages/terms_and_conditions', to: 'pages#terms_and_conditions'

  devise_for :users
  resources :users, only: [:show] do

  	member do
  		get 'edit_profile'
  		patch 'update_profile'
  		get 'edit_avatar'
  		patch 'update_avatar'
  	end
    
  end

  resources :apartments do
    resources :photos, only: [:destroy]
    resources :bookings, only: [:new] #add bookings new under apartments

    collection do
      get 'district/:district', to: 'apartments#index_district'
    end

    member do
      get 'sold', to: 'apartments#sold'
    end
  end

  resources :bookings, except: [:new] do #remove new from bookings
    resources :payments, only: [:new, :create]
  end

end

app/models/apartment.rb
class Apartment < ApplicationRecord
  has_many :photos
  has_many :bookings
  belongs_to :user

  def self.options_for_district
  	["Central and Western", "Eastern", "Southern", "Wan Chai", "Kowloon City", "Kwun Tong", "Sham Shui Po", "Wong Tai Sin", "Yau Tsim Mong", "Islands", "Kwai Tsing", "North", "Sai Kung", "Sha Tin", "Tai Po", "Tsuen Wan", "Tuen Mun", "Yeun Long"]
  end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy, :sold]
  skip_before_action :authenticate_user!, only: [:index, :index_district]

  def index
    if(params[:query].present?)
      @apartments = policy_scope(Apartment).where("address ILIKE ?", "%#{ params[:query]}%")
    else
      @apartments = policy_scope(Apartment).all
    end
    
    authorize :apartment, :index?
  end

  def index_district
    @district = params["district"]
    @apartments = policy_scope(Apartment).where(district: params[:district]).order(created_at: :desc)

    if @apartments.count == 0
      @apartments = policy_scope(Apartment).order(created_at: :desc)
    end

    authorize :apartment, :index_district?
    render :index
  end

  def show
    authorize @apartment
  end

  def new
    @apartment = Apartment.new
    authorize @apartment
  end

  def edit
    authorize @apartment
  end

  def create
    @apartment = Apartment.new(apartment_params)
    @apartment.status = 'Available'
    @apartment.user = current_user

    authorize @apartment

    if @apartment.save
      unless params[:photos].nil?
        params[:photos][:img].each do |a|
          @photo = @apartment.photos.create!(:img => a)
          # @photo = Photo.create(apartment: @apartment, img: a)
        end
      end
      redirect_to @apartment, notice: 'Apartment was successfully created.'
    else
      render :new, alert: 'Error on creating apartment.'
    end
  end

  def update
    authorize @apartment

    if @apartment.update(apartment_params)
      unless params[:photos].nil?
        params[:photos][:img].each do |a|
          @photo = @apartment.photos.create!(:img => a)
        end
      end
      redirect_to @apartment, notice: 'Apartment was successfully updated.'
    else
      render :edit, alert: 'Error on updating apartment.'
    end
  end

  def destroy
    authorize @apartment
    @apartment.destroy

    redirect_to apartments_url, notice: 'Apartment was successfully destroyed.'
  end

  def sold
    authorize @apartment

    @apartment.update(status: "Sold")
    redirect_to @apartment, notice: 'Apartment is sold.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:status, :address, :price, :latitude, :longtitude, :district, :description, :size, :year_built, :bedrooms, :elevator, :furnished, photos_attributes: [:img])
    end
end

app/views/apartments/_apartment_photos.erb
<div class="apartment_photo_container my-4" id="gallery">
    <% apartment.photos.each do |photo| %>
    	<%= link_to cl_image_path(photo.img) do %>
           <%= cl_image_tag photo.img, :transformation => { :width => 200, :height => 200, :crop => "fill" }, :class => "photo-original" %>
        <% end %>
   
    <% end %>
</div>

app/views/apartments/_form.html.erb
<div class="apartment_form">
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>"></script>
  <%= simple_form_for(@apartment) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :status, collection: ["Available", "Sold"], required: true %>
      <%= f.input :district, collection: Apartment::options_for_district, required: true %>
      <%= f.input :address, required: true %>
      <%= f.input :latitude, as: :hidden %>
      <%= f.input :longtitude, as: :hidden %>
      <div class="my-4">
        <label>Drag the marker to position the apartment</label>
        <div id="map"></div>
      </div>
      
      <%= f.input :description, required: true %>
      <%= f.input :price, required: true %>
      <%= f.input :size, required: true %>
      <%= f.input :year_built, collection: (1950..Date.today.year), required: true %>
      <%= f.input :bedrooms, required: true %>
      <%= f.input :elevator %>
      <%= f.input :furnished %>


      <%= f.label "Add Photos" %><br>
      <%= f.file_field :img, :multiple => true, name: "photos[img][]" %>


    </div>

    <!-- list each apartment photo, with destroy button -->
    <% @apartment.photos.each do |photo| %>
      <div class="form-inputs my-4">
        <%= cl_image_tag photo.img, :transformation => { :width => 200, :crop => "pad" }, :cloud_name => "preface" %>
        <%= link_to 'Destroy', apartment_photo_path(@apartment, photo), method: :delete, data: { confirm: 'Are you sure?' }, class: "ml-2 btn btn-sm btn-danger" %>
      </div>
    <% end %>
    <!-- end of apartment photos -->

    <div class="form-actions">
      <%= f.button :submit, :class => 'btn btn-primary my-4'%>
    </div>
  <% end %>
</div>

app/views/apartments/edit.html.erb
<div class="container my-4">
	<div class="row">
		<div class="col-lg-8 offset-lg-2">
			<h1>Editing Apartment</h1>

			<%= render 'form', apartment: @apartment %>

			<%= link_to 'Show', @apartment %>
			<%= link_to 'Back', apartments_path %>
		</div>
	</div>
</div>

app/views/apartments/index.html.erb
<div class="apartment_index_page">
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>"></script>

  <div id="map-data-container" style="display:none">
    <ul>
    <% @apartments.each do |apartment| %>
      <% img = image_path("shared/apartment_default.jpg") %>
      <% if apartment.photos.count > 0 %>
        <% img = cl_image_path(apartment.photos[0].img, :cloud_name => "preface", :transformation => { :width => 200, :height=> 200, :crop => "fill" }) %>
      <% end %>
      <li class="map-data" data-id="<%= apartment[:id]%>" data-address="<%= apartment[:address] %>" data-latitude="<%= apartment[:latitude] %>" data-longtitude="<%= apartment[:longtitude] %>" data-img="<%= img %>"></li>
    <% end %>
    </ul>
  </div>

  <div class="row">
    <div class="d-none d-md-block w-50">
      <div id="map"></div>
    </div>
    <div class="apartment-card-container">
      <% @apartments.each do |apartment| %>
        <div class="apartment-card">
          <%= link_to apartment.address, apartment_path(apartment), class: "apartment_link" %>

          <% if policy(apartment).edit? %>
            <%= link_to "Edit", edit_apartment_path(apartment), class: "ml-1 btn btn-sm btn-primary" %>
          <% end %>

          <% if policy(apartment).destroy? %>
            <%= link_to 'Destroy', apartment_path(apartment), method: :delete, data: { confirm: 'Are you sure?' }, class: "ml-1 btn btn-sm btn-danger" %>
          <% end %>

          <% if policy(apartment).sold? && apartment.status != "Sold" %>
            <%= link_to 'Set Sold', sold_apartment_path(apartment), class: "ml-1 btn btn-sm btn-success" %>
          <% end %>



        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/apartments/index_district.html.erb
<div class="apartment_index_page">
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>"></script>

  <div id="map-data-container" style="display:none">
    <ul>
    <% @apartments.each do |apartment| %>
      <% img = image_path("shared/apartment_default.jpg") %>
      <% if apartment.photos.count > 0 %>
        <% img = cl_image_path(apartment.photos[0].img, :cloud_name => "preface", :transformation => { :width => 200, :height=> 200, :crop => "fill" }) %>
      <% end %>
      <li class="map-data" data-id="<%= apartment[:id]%>" data-address="<%= apartment[:address] %>" data-latitude="<%= apartment[:latitude] %>" data-longtitude="<%= apartment[:longtitude] %>" data-img="<%= img %>"></li>
    <% end %>
    </ul>
  </div>

  <div class="row">
    <div class="d-none d-md-block w-50">
      <div id="map"></div>
    </div>
    <div class="apartment-card-container">
      <% @apartments.each do |apartment| %>
        <div class="apartment-card">
          <%= link_to apartment.address, apartment_path(apartment), class: "apartment_link" %>

          <% if policy(apartment).edit? %>
            <%= link_to "Edit", edit_apartment_path(apartment), class: "ml-1 btn btn-sm btn-primary" %>
          <% end %>

          <% if policy(apartment).destroy? %>
            <%= link_to 'Destroy', apartment_path(apartment), method: :delete, data: { confirm: 'Are you sure?' }, class: "ml-1 btn btn-sm btn-danger" %>
          <% end %>

        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/apartments/new.html.erb
<div class="container my-4">
	<div class="row">
		<div class="col-lg-8 offset-lg-2">
			<h1>New Apartment</h1>

			<%= render 'form', apartment: @apartment %>

			<%= link_to 'Back', apartments_path, class: "btn btn-primary my-4" %>
		</div>
	</div>

</div>

app/views/apartments/show.html.erb
<div class="apartment_show_page">
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>"></script>
    <div class="container my-4">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <div id="map-data-container" style="display:none">
                    <ul>
                        <% img = image_path("shared/apartment_default.jpg") %>
                        <% if @apartment.photos.count > 0 %>
                        <% img = cl_image_path(@apartment.photos[0].img, :cloud_name => "preface", :transformation => { :width => 200, :height=> 200, :crop => "fill" }) %>
                        <% end %>
                        <li class="map-data" data-id="<%= @apartment[:id]%>" data-address="<%= @apartment[:address] %>" data-latitude="<%= @apartment[:latitude] %>" data-longtitude="<%= @apartment[:longtitude] %>" data-img="<%= img %>"></li>
                    </ul>
                </div>
                <div id="map"></div>
                <div class="card">
                    <h5 class="card-title mx-4 mt-4 mb-0"><%= @apartment.description %></h5>
                    <div class="card-body">
                        <span class="badge <%= @apartment.status == 'Available' ? 'badge-success' : 'badge-secondary' %>"><%= @apartment.status %></span>

                        <div class="my-3">
                            <small>District:</small><br>
                            <%= @apartment.district %>
                        </div>

                        <div class="my-3">
                            <small>Address:</small><br>
                            <%= @apartment.address %>
                        </div>

                        <div class="my-3">
                            <small>Price:</small><br>
                            <%= humanized_money_with_symbol(@apartment.price) %>
                        </div>

                        <div class="my-3">
                            <small>Description:</small><br>
                            <%= @apartment.description %>
                        </div>

                        <div class="my-3">
                            <small>Size:</small><br>
                            <%= @apartment.size %> sqft
                        </div>

                        <div class="my-3">
                            <small>Year built:</small><br>
                            <%= @apartment.year_built %>
                        </div>

                        <div class="my-3">
                            <%= @apartment.bedrooms %> bedrooms
                        </div>

                        <div class="my-3">
                            <small>Elevator:</small><br>
                            <%= @apartment.elevator ? "Yes" : "No" %>
                        </div>

                        <div class="my-3">
                            <small>Furnished:</small><br>
                            <%= @apartment.furnished ? "Yes" : "No" %>
                        </div>

                        <div class="my-3">
                            <%= render 'apartment_photos', apartment: @apartment %>
                        </div>
                    </div>
                </div>

                <div class="my-4">
                    

                    <%= link_to 'Create Booking to View', new_apartment_booking_path(@apartment), class: "btn btn-primary " %>
                </div>
                <div>
                    <%= link_to 'Back', apartments_path, :class => 'btn btn-secondary' %>
                    <% if policy(@apartment).edit? %>
                        <%= link_to 'Edit', edit_apartment_path(@apartment), :class => 'btn btn-primary' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>